# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BiometrixTest
                                 A QGIS plugin
 BiometrixTest
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-29
        copyright            : (C) 2025 by AWSI
        email                : gabriel.sultan@aws-institut.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BiometrixTest class from file BiometrixTest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .BiometrixTest import BiometrixTest
    return BiometrixTest(iface)
